name: Create a PR

on:
  push:
    branches:
      - main
      - master

concurrency:
  group: ci-planning-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  hello:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Get OIDC token and call edge function
        run: |
          TOKEN=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=release-plan-token" | jq -r .value)
          GH_TOKEN=$(curl -H "Authorization: Bearer $TOKEN" https://release-plan-token.netlify.app/token)
          echo "GH_TOKEN=$GH_TOKEN" >> $GITHUB_ENV

      - run: echo `date` >> time.txt
      - uses: peter-evans/create-pull-request@v8
        with:
          commit-message: "Pretend to do some stuff"
          labels: "internal"
          branch: test-preview
          title: testing pull requests
          token: ${{ env.GH_TOKEN }}
          body: |
            Let us see if CI runs on this PR then!
